# Generated by Django 4.1.13 on 2024-05-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BR_CaracteristicasTerreno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('areaTotalTerreno', models.FloatField(blank=True, null=True)),
                ('areaTotalTerreno_privativa', models.FloatField(blank=True, null=True)),
                ('areaTotalTerreno_comum', models.FloatField(blank=True, null=True)),
                ('areaTotalConstruida', models.FloatField(blank=True, null=True)),
                ('areaTotalConstruida_privada', models.FloatField(blank=True, null=True)),
                ('areaTotalConstruida_comum', models.FloatField(blank=True, null=True)),
                ('numCasas', models.IntegerField(blank=True, null=True)),
                ('numTorres', models.IntegerField(blank=True, null=True)),
                ('totalUnidadesPrivativas', models.IntegerField(blank=True, null=True)),
                ('limitacao', models.CharField(blank=True, max_length=255, null=True)),
                ('topografia', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.CharField(blank=True, max_length=255, null=True)),
                ('numVagas', models.IntegerField(blank=True, null=True)),
                ('nivelamento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_ContatoPessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_DocumentoPessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
                ('numeroDocumento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_EnderecoCorrespondencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoLogradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('nomeLogradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('UF', models.CharField(blank=True, max_length=2, null=True)),
                ('CEP', models.CharField(blank=True, max_length=20, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_EnderecoImovel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_ImovelFiscal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inscricaoImobiliaria', models.CharField(max_length=255)),
                ('matriculaImobiliaria', models.CharField(max_length=255)),
                ('descricaoImovel', models.TextField(blank=True, null=True)),
                ('dataCriacao', models.DateField(blank=True, null=True)),
                ('inscricaoAnterior', models.CharField(blank=True, max_length=255, null=True)),
                ('loteamento', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('setor', models.CharField(blank=True, max_length=255, null=True)),
                ('quadra', models.CharField(blank=True, max_length=255, null=True)),
                ('lote', models.CharField(blank=True, max_length=255, null=True)),
                ('unidade', models.CharField(blank=True, max_length=255, null=True)),
                ('testada', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_Infraestrutura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('energiaEletrica', models.BooleanField(default=False)),
                ('abastecimentoAgua', models.BooleanField(default=False)),
                ('iluminacaoPublica', models.BooleanField(default=False)),
                ('esgoto', models.BooleanField(default=False)),
                ('coletaLixo', models.BooleanField(default=False)),
                ('pavimentacao', models.BooleanField(default=False)),
                ('telefonia', models.BooleanField(default=False)),
                ('arborizacao', models.BooleanField(default=False)),
                ('passeio', models.BooleanField(default=False)),
                ('drenagemPluvial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BR_Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPessoa', models.CharField(blank=True, max_length=255, null=True)),
                ('codContribuinte', models.CharField(blank=True, max_length=255, null=True)),
                ('papel', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_contatoPessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_contatopessoa')),
                ('fk_documentoPessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_documentopessoa')),
            ],
        ),
        migrations.CreateModel(
            name='BR_PessoaFisica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoCivil', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_PessoaJuridica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeFantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('razaoSocial', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_TrechoLogradouro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_Tributo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorVenal', models.FloatField(blank=True, null=True)),
                ('IPTU', models.FloatField(blank=True, null=True)),
                ('isencaoIPTU', models.BooleanField(default=False)),
                ('fatorTerreno', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=255, null=True)),
                ('fieldDescription', models.CharField(max_length=5000, null=True)),
                ('fieldModel', models.CharField(max_length=255, null=True)),
                ('fieldType', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BR_ImovelCadastral',
        ),
        migrations.DeleteModel(
            name='BR_ImovelCondominio',
        ),
        migrations.DeleteModel(
            name='BR_ImovelLegal',
        ),
        migrations.DeleteModel(
            name='BR_Logradouro',
        ),
        migrations.DeleteModel(
            name='BR_Parcela',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.AddField(
            model_name='br_caracteristicasedificacao',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='br_caracteristicasedificacao',
            name='cobertura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldmatching',
            name='matchingTableName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelodinamico',
            name='pdfFile',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='acabamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='condicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='conservacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='elevador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='esquadria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='estrutura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='orientacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='posicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='tipologia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='utilizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='br_caracteristicasedificacao',
            name='utilizacaoSecundaria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modelodinamico',
            name='isConcluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='br_pessoa',
            name='fk_pessoaFisica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_pessoafisica'),
        ),
        migrations.AddField(
            model_name='br_pessoa',
            name='fk_pessoaJuridica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_pessoajuridica'),
        ),
        migrations.AddField(
            model_name='br_imovelfiscal',
            name='fk_caracteristicasEdificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_caracteristicasedificacao'),
        ),
        migrations.AddField(
            model_name='br_imovelfiscal',
            name='fk_caracteristicasTerreno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_caracteristicasterreno'),
        ),
        migrations.AddField(
            model_name='br_imovelfiscal',
            name='fk_enderecoImovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_enderecoimovel'),
        ),
        migrations.AddField(
            model_name='br_imovelfiscal',
            name='fk_infraestrutura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_infraestrutura'),
        ),
        migrations.AddField(
            model_name='br_imovelfiscal',
            name='fk_pessoa',
            field=models.ManyToManyField(to='api.br_pessoa'),
        ),
        migrations.AddField(
            model_name='br_imovelfiscal',
            name='fk_trechoLogradouro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_trechologradouro'),
        ),
        migrations.AddField(
            model_name='br_imovelfiscal',
            name='fk_tributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_tributo'),
        ),
    ]
