# Generated by Django 4.1.13 on 2024-05-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodinamico',
            name='isConcluded',
            field=models.BooleanField(null=True),
        ),
    ]
