# Generated by Django 4.1.13 on 2024-03-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_id_alter_modelodinamico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='data_nasc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rrr',
            name='data_inicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rrr',
            name='data_termino',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
