# Generated by Django 4.1.13 on 2024-06-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_br_caracteristicasterreno_br_contatopessoa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='CEP',
            new_name='CEP_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='UF',
            new_name='UF_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='bairro',
            new_name='bairro_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='classificacao',
            new_name='classificacao_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='complemento',
            new_name='complemento_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='municipio',
            new_name='municipio_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='nomeLogradouro',
            new_name='nomeLogradouro_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='numero',
            new_name='numero_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecocorrespondencia',
            old_name='tipoLogradouro',
            new_name='tipoLogradouro_correspondencia',
        ),
        migrations.RenameField(
            model_name='br_enderecoimovel',
            old_name='bairro',
            new_name='bairro_imovel',
        ),
        migrations.RenameField(
            model_name='br_enderecoimovel',
            old_name='cep',
            new_name='cep_imovel',
        ),
        migrations.RenameField(
            model_name='br_enderecoimovel',
            old_name='complemento',
            new_name='complemento_imovel',
        ),
        migrations.RenameField(
            model_name='br_enderecoimovel',
            old_name='numero',
            new_name='numero_imovel',
        ),
    ]
