# Generated by Django 4.1.13 on 2024-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fieldmatching_matchingtablename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodinamico',
            name='isConcluded',
            field=models.BooleanField(default=False),
        ),
    ]
