# Generated by Django 4.1.13 on 2024-06-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cep_br_enderecocorrespondencia_cep_correspondencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='br_pessoa',
            name='fk_enderecoCorrespondencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.br_enderecocorrespondencia'),
        ),
        migrations.AddField(
            model_name='fieldmatching',
            name='fk_modeloDinamico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.modelodinamico'),
        ),
    ]
