# Generated by Django 4.1.13 on 2024-04-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_equipamentopublico_id_modelodinamico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BR_CaracteristicasEdificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(null=True)),
                ('tipologia', models.IntegerField(null=True)),
                ('elevador', models.BooleanField()),
                ('posicao', models.IntegerField(null=True)),
                ('conservacao', models.IntegerField(null=True)),
                ('orientacao', models.IntegerField(null=True)),
                ('esquadria', models.IntegerField(null=True)),
                ('estrutura', models.IntegerField(null=True)),
                ('acabamento', models.IntegerField(null=True)),
                ('utilizacao', models.IntegerField(null=True)),
                ('utilizacaoSecundaria', models.IntegerField(null=True)),
                ('condicao', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_ImovelCadastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculaImobiliaria_IC', models.IntegerField(null=True)),
                ('inscricaoImobiliaria', models.IntegerField(null=True)),
                ('idCadastro_IC', models.IntegerField(null=True)),
                ('areaTerreno', models.FloatField()),
                ('tipoImovel', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_ImovelCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaTotalTerreno', models.FloatField()),
                ('areaTotalTerreno_privativa', models.FloatField()),
                ('areaTotalTerreno_comum', models.FloatField()),
                ('areaTotalConstruida', models.FloatField()),
                ('areaTotalConstruida_privada', models.FloatField()),
                ('areaTotalConstruida_comum', models.FloatField()),
                ('numCasas', models.IntegerField(null=True)),
                ('numTorres', models.IntegerField(null=True)),
                ('totalUnidadesPrivativas', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BR_ImovelLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ORIP', models.IntegerField(null=True)),
                ('matricula', models.IntegerField(null=True)),
                ('descricaoImovel', models.CharField(blank=True, max_length=1000, null=True)),
                ('classesUsoSoloReg', models.IntegerField(null=True)),
                ('inscricaoImob', models.IntegerField(null=True)),
                ('idCadastro_IL', models.IntegerField(null=True)),
                ('dataAbertura', models.DateField()),
                ('matriculaOrigem', models.IntegerField(null=True)),
                ('matriculaNova', models.IntegerField(null=True)),
                ('valorImovel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BR_Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoLogradouro_Log', models.IntegerField(null=True)),
                ('nomeAnterior', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeLogradouro_Log', models.CharField(blank=True, max_length=100, null=True)),
                ('cep_Log', models.IntegerField(null=True)),
                ('atoCriacao', models.CharField(blank=True, max_length=100, null=True)),
                ('dataCriacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BR_Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLote', models.IntegerField(null=True)),
                ('limitacao', models.IntegerField(null=True)),
                ('tipoTopografia', models.IntegerField(null=True)),
                ('numVagasCobertas', models.IntegerField(null=True)),
                ('situacao', models.IntegerField(null=True)),
                ('adequacaoOcupacao', models.IntegerField(null=True)),
                ('nivelamento', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoLogradour_End', models.IntegerField(null=True)),
                ('nomeLogradouro_End', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cep_End', models.IntegerField(null=True)),
            ],
        ),
    ]
