# Generated by Django 4.1.13 on 2024-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_br_pessoa_fk_enderecocorrespondencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmatching',
            name='fk_modeloDinamico',
        ),
        migrations.AddField(
            model_name='fieldmatching',
            name='fk_modeloDinamico_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldmatching',
            name='fk_modeloDinamico_iduser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='modelodinamico',
            unique_together={('id', 'iduser')},
        ),
        migrations.AddConstraint(
            model_name='fieldmatching',
            constraint=models.UniqueConstraint(fields=('fk_modeloDinamico_id', 'fk_modeloDinamico_iduser', 'iduserdata'), name='unique_fieldmatching'),
        ),
    ]
