# Generated by Django 4.1.13 on 2024-04-10 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_br_caracteristicasedificacao_br_imovelcadastral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo_entrada', models.CharField(max_length=255)),
                ('nome_campo_referencia', models.CharField(max_length=255)),
                ('modelo_referencia', models.CharField(max_length=255)),
                ('data_matching', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'nome_campo_entrada')},
            },
        ),
    ]
