# Generated by Django 4.1.13 on 2024-04-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_campomatch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campomatch',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='campomatch',
            name='usuario',
        ),
    ]
