# Generated by Django 4.1.13 on 2024-04-14 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_campomatch_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campomatch',
            name='modelo_referencia',
        ),
    ]
