# Generated by Django 4.1.13 on 2024-04-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_campomatch_modelo_referencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campomatch',
            old_name='nome_campo_entrada',
            new_name='inputField',
        ),
        migrations.RenameField(
            model_name='campomatch',
            old_name='nome_campo_referencia',
            new_name='referenceField',
        ),
        migrations.RenameField(
            model_name='campomatch',
            old_name='data_matching',
            new_name='timestamp',
        ),
    ]
