# Generated by Django 4.1.13 on 2024-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0008_remove_fieldmatching_unique_fieldmatching_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmatching',
            name='fk_modeloDinamico',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='modelodinamico',
            name='iduser',
            field=models.IntegerField(null=True),
        ),
    ]
