# Generated by Django 4.1.13 on 2024-04-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_campomatch_tablename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampoMatch',
            new_name='FieldMatching',
        ),
    ]
