# Generated by Django 4.1.13 on 2024-04-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_campomatch_fieldmatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmatching',
            name='iduserdata',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
