# Generated by Django 4.1.13 on 2024-04-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fieldmatching_iduserdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometria',
            name='id_modeloDinamico',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='id_modeloDinamico',
        ),
        migrations.DeleteModel(
            name='EquipamentoPublico',
        ),
        migrations.DeleteModel(
            name='Geometria',
        ),
        migrations.DeleteModel(
            name='Proprietario',
        ),
    ]
