# Generated by Django 4.1.13 on 2024-04-24 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_geometria_id_modelodinamico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelodinamico',
            old_name='data',
            new_name='dataCSV',
        ),
        migrations.AddField(
            model_name='modelodinamico',
            name='dataJSON',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
