# Generated by Django 4.1.13 on 2024-04-24 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_adminuser_modelodinamico_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodinamico',
            name='iduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
