# Generated by Django 4.1.13 on 2024-04-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_modelodinamico_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodinamico',
            name='iduser',
            field=models.IntegerField(null=True),
        ),
    ]
