# Generated by Django 4.1.13 on 2024-04-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_modelodinamico_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
            ],
        ),
    ]
